Update my-second-actions.yml

diff --git a/.github/workflows/my-second-actions.yml b/.github/workflows/my-second-actions.yml
--- a/.github/workflows/my-second-actions.yml
+++ b/.github/workflows/my-second-actions.yml
@@ -12,6 +12,15 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+
+    - name: Check if Python version exists
+      run: |
+        if ! command -v python${{ matrix.python-version }} &> /dev/null; then
+          echo "Python ${{ matrix.python-version }} not found. Skipping this job..."
+          exit 0
+        fi
+
+    
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
